name: CD
on:
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: BalliAsghar/killport
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Grab SHA256
        id: sha256
        env:
          VERSION: ${{ steps.latest_release.outputs.release }}
        run: |
          echo "::set-output name=sha256::$(curl -sL https://github.com/BalliAsghar/killport/archive/refs/tags/${VERSION}.tar.gz | sha256sum | cut -d ' ' -f 1)"
      - name: Update Formula File
        env:
          SHA256: ${{ steps.sha256.outputs.sha256 }}
          VERSION: ${{ steps.latest_release.outputs.release }}
        working-directory: Formula
        run: |
          sed -i "s/refs\/tags\/v[0-9]\+\.[0-9]\+\.[0-9]\+/refs\/tags\/${VERSION}/" killport.rb
          sed -i "s/sha256 \"[a-z0-9]\+\"/sha256 \"${SHA256}\"/" killport.rb
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
