name: CD
on:
  workflow_dispatch:
    inputs:
      sha256:
        description: "SHA256 of the release"
        required: true
        default: "sha256"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: BalliAsghar/killport
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Formula File
        env:
          SHA256: ${{ inputs.sha256 }}
          VERSION: ${{ steps.latest_release.outputs.release }}
        working-directory: Formula
        run: |
          sed -i "s/refs\/tags\/[0-9]\+\.[0-9]\+\.[0-9]\+/refs\/tags\/${VERSION}/" killport.rb
          sed -i "s/sha256 \"[a-z0-9]\+\"/sha256 \"${SHA256}\"/" killport.rb
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add killport.rb
          git commit -m "Formula Updated to ${VERSION}"
          git push
