name: CD-PC
on:
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: BalliAsghar/partial-clone
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get SHA256
        env:
          VERSION: ${{ steps.latest_release.outputs.release }}
        run: |
          echo "sha256=$(curl -sL curl -sL https://github.com/BalliAsghar/partial-clone/archive/refs/tags/${VERSION}.tar.gz | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Update Formula File
        env:
          SHA256: ${{ env.sha256 }}
          VERSION: ${{ steps.latest_release.outputs.release }}
        working-directory: Formula
        run: |
          sed -i "s/refs\/tags\/v[0-9]\+\.[0-9]\+\.[0-9]\+/refs\/tags\/${VERSION}/" pc.rb
          sed -i "s/sha256 \"[a-z0-9]\+\"/sha256 \"${SHA256}\"/" pc.rb
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated Change: partial-clone Updated"
